services:
  - type: web
    name: mobicryp-slideshow
    runtime: static
    buildCommand: ""
    staticPublishPath: "."
    pullRequestPreviewsEnabled: true
    envVars:
      - key: CACHE_CONTROL
        value: no-cache, no-store, must-revalidate
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache, no-store, must-revalidate
      - path: /*
        name: Pragma
        value: no-cache
      - path: /*
        name: Expires
        value: "0"
      - path: /*
        name: X-Frame-Options
        value: DENY