services:
  - type: web
    name: mobicryp-slideshow
    runtime: static
    buildCommand: ""
    staticPublishPath: "."
    pullRequestPreviewsEnabled: true
    envVars:
      - key: CACHE_CONTROL
        value: max-age=3600
    headers:
      - path: /*
        name: X-Frame-Options
        value: DENY