services:
  - type: web
    name: mobicryp-enhanced-presentation
    env: static
    buildCommand: echo "Static site, no build required"
    staticPublishPath: ./slides
    # No rewrites - let the server serve files directly
    autoDeploy: true