services:
  - type: web
    name: mobicryp-slideshow
    runtime: static
    buildCommand: ""
    staticPublishPath: "."
    pullRequestPreviewsEnabled: true
    envVars:
      - key: CACHE_CONTROL
        value: max-age=3600
    headers:
      - path: /*
        name: X-Frame-Options
        value: DENY
      - path: /css/*
        name: Cache-Control
        value: public, max-age=31536000, immutable
      - path: /js/*
        name: Cache-Control
        value: public, max-age=31536000, immutable
      - path: /images/*
        name: Cache-Control
        value: public, max-age=31536000, immutable